/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "Article content shows here.": "Article content shows here.",
    "Article title shows here": "Article title shows here and things like that",
    "Daily Feed": "中国",
    "Date": "Date",
    "Done": "Done",
    "Error": "Error",
    "Failed to load a valid feed.": "Failed to load a valid feed.",
    "Loading": "Loading",
    "No <channel> element in feed.": "No <channel> element in feed.",
    "No <feed> element in Atom feed.": "No <feed> element in Atom feed.",
    "No feed URL supplied.": "No feed URL supplied.",
    "The feed could not be understood.": "The feed could not be understood.",
    "Untitled": "Untitled"
};
