/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "articleDate": { "creationFunction": "CreateText", "text": "Publish Date" },
    "articleDescription": { "creationFunction": "CreateText", "text": "Article" },
    "articleTitle": { "creationFunction": "CreateText", "text": "Title" },
    "backToHeadlines": { "creationFunction": "CreatePushButton", "initialHeight": 30, "initialWidth": 120, "leftImageWidth": 16, "rightImageWidth": 5, "text": "Back" },
    "feedName": { "creationFunction": "CreateText", "text": "我是汉语学生" },
    "headlineDescription": { "creationFunction": "CreateText", "text": "Article Description" },
    "headlineList": { "creationFunction": "CreateList", "dataArray": ["Article Title", "Item 2", "Item 3"], "dataSourceName": "headlineList", "labelElementId": "headlineTitle", "listStyle": "List.EDGE_TO_EDGE", "sampleRows": 2, "useDataSource": true },
    "headlineTitle": { "creationFunction": "CreateText", "text": "Article Title" },
    "olderArticlesLabel": { "creationFunction": "CreateText", "text": "多新词" },
    "secondHeadlines": { "creationFunction": "CreateList", "dataArray": ["Item 1", "Item 2", "Item 3"], "dataSourceName": "secondHeadlineList", "labelElementId": "secondHeadlineTitle", "listStyle": "List.EDGE_TO_EDGE", "sampleRows": 2, "useDataSource": true },
    "secondHeadlineTitle": { "creationFunction": "CreateText", "text": "Article Title" },
    "StackLayout": { "creationFunction": "CreateStackLayout", "subviewsTransitions": [{ "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }] },
    "todaysDate": { "creationFunction": "CreateText", "text": "DATE" }
};
