/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "bottomRectangleShape": { "creationFunction": "CreateShape", "leftImageWidth": 10, "rightImageWidth": 10 },
    "dateText": { "creationFunction": "CreateText", "text": "Daily Feed" },
    "done": { "creationFunction": "CreateGlassButton", "onclick": "showFront", "text": "Done" },
    "entryDescription": { "creationFunction": "CreateText", "text": "Article content shows here." },
    "entryTitle": { "creationFunction": "CreateText", "text": "Article title shows here" },
    "info": { "backgroundStyle": "black", "creationFunction": "CreateInfoButton", "foregroundStyle": "black", "frontID": "front", "onclick": "showBack" },
    "text": { "creationFunction": "CreateText", "text": "http://cn.robrohan.com" },
    "text1": { "creationFunction": "CreateText", "text": "© 2007-2009 Rob Rohan" },
    "text2": { "creationFunction": "CreateText", "text": "All Rights Reserved." },
    "text3": { "creationFunction": "CreateText", "text": "v1.5" }
};
